project:
  type: website
  output-dir: docs
  resources: posters
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!posters/"

website:
  title: "picture-duration-directed-forgetting"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posters/poster.html
        text: Poster
  sidebar:
    contents: vignettes

format:
  html:
    theme: minty
    css: styles.css
    toc: true



